version: '3.2'

services:
  devdns:
    # Provides local dns resolv via
    # https://github.com/ruudud/devdns
    # by default it provides the (.test) local dev domain
    image: ruudud/devdns
    container_name: internal-devdns
    ports: ["53:53/udp"]
    networks:
      default:
        ipv4_address: '172.240.255.254'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Copenhagen
      HOSTMACHINE_IP: 192.168.99.100
      # A records for any external device, expose vm ip
      EXTRA_HOSTS: "devdns.test=192.168.99.100 migrid.test=192.168.99.100
      www.migrid.test=172.240.255.253 oid.migrid.test=172.240.255.253"
      NAMING: full

  internal-migrid:
    image: nielsbohr/migrid:edge
    container_name: internal-migrid
    environment:
      TZ: Europe/Copenhagen
    ports: ["80:80/tcp", "443:443/tcp"]
    dns: '172.240.255.254'
    networks:
      default:
        ipv4_address: '172.240.255.253'
    depends_on:
      - devdns
    volumes:
      - type: volume
        source: certs
        target: /home/mig/certs
    env_file:
      - httpd.env
    command: httpd -D FOREGROUND

volumes:
  certs:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.240.0.0/16