version: '3.7'

services:
  devdns:
    image: ruudud/devdns
    container_name: devdns
    ports:
      - "53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Copenhagen

  migrid:
    image: nielsbohr/migrid:$BUILD_TYPE
    container_name: migrid
    environment:
      TZ: Europe/Copenhagen
    depends_on:
      - devdns
    networks:
      default:
        aliases:
          - cert.migrid.test
          - ext.migrid.test
          - oid.migrid.test
          - sid.migrid.test
          - www.migrid.test
    volumes:
      - type: volume
        source: httpd
        target: /etc/httpd/
      - type: volume
        source: mig
        target: /home/mig/mig
      - type: volume
        source: certs
        target: /etc/httpd/MiG-certificates
      - type: volume
        source: state
        target: /home/mig/state
    env_file:
      - migrid-httpd.env
    command: /app/docker-entry.sh -u dev@dev.dk -p Passw0rd123

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - migrid
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx-proxy.conf:/etc/nginx/conf.d/migrid.conf
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/cert.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/ext.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/oid.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/sid.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/cert.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/ext.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/oid.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/sid.migrid.test.key
    - ./certs/MiG/*.migrid.test/dhparams.pem:/etc/nginx/dhparam/dhparams.pem

volumes:
  certs:
    driver: local
    driver_opts:
      # Volume for generated certificates (provided by migrid)
      type: none
      device: $PWD/certs
      o: bind

  httpd:
    # Volume used for httpd config (provided by migrid)
    driver: local
    driver_opts:
      type: none
      device: $PWD/httpd
      o: bind

  mig:
    # Volume used to contain the migrid configuration (provided by migrid)
    driver: local
    driver_opts:
      type: none
      device: $PWD/mig
      o: bind

  state:
      # Volume used to contain the migrid state (provided by migrid)
      driver: local
      driver_opts:
        type: none
        device: $PWD/state
        o: bind
