version: '3.7'

services:
  devdns:
    image: ruudud/devdns
    container_name: devdns
    ports: ["53:53/udp"]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Copenhagen
      EXTRA_HOSTS: "migrid.test=127.0.0.1"

  migrid:
    image: nielsbohr/migrid:edge
    container_name: migrid
    environment:
      TZ: Europe/Copenhagen
    depends_on:
      - devdns
    networks:
      default:
        aliases:
          - migrid.test
          - io.migrid.test
          - www.migrid.test
          - oid.migrid.test
          - sid.migrid.test
    volumes:
      - type: volume
        source: httpd
        target: /etc/httpd/
      - type: volume
        source: mig
        target: /home/mig/mig
      - type: volume
        source: certs
        target: /etc/httpd/MiG-certificates
      - type: volume
        source: state
        target: /home/mig/state
      # Mount the BASH runtime env & migrid.test.0 resource
      - ./res/BASH-ANY-1:/home/mig/state/re_home/BASH-ANY-1
      - ./res/migrid.test.0:/home/mig/state/resource_home/migrid.test.0
      - ./example_notebooks/test_notebook.ipynb:/home/mig/state/user_home/+C=dk+ST=dk+L=NA+O=org+OU=NA+CN=devuser+emailAddress=dev@dev.dk/test_notebook.ipynb
      - ./res/test_job.py:/home/mig/state/user_home/+C=dk+ST=dk+L=NA+O=org+OU=NA+CN=devuser+emailAddress=dev@dev.dk/test_job.py
    env_file:
      - migrid-httpd.env
    command: /app/docker-entry.sh -u dev@dev.dk -p Passw0rd123

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - migrid
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx-proxy.conf:/etc/nginx/conf.d/migrid.conf
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/oid.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/sid.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/oid.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/sid.migrid.test.key

volumes:
  certs:
    driver_opts:
      # Volume for generated certificates (provided by migrid)
      type: none
      device: $PWD/certs
      o: bind

  httpd:
    # Volume used for httpd config (provided by migrid)
    driver_opts:
      type: none
      device: $PWD/httpd
      o: bind

  mig:
    # Volume used to contain the migrid configuration (provided by migrid)
    driver_opts:
      type: none
      device: $PWD/mig
      o: bind

  state:
      # Volume used to contain the migrid state (provided by migrid)
      driver_opts:
        type: none
        device: $PWD/state
        o: bind
