version: '3.7'

services:
  devdns:
    image: ruudud/devdns
    container_name: devdns
    ports:
        - "127.0.0.1:53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Copenhagen

  migrid:
    image: nielsbohr/migrid:$BUILD_TYPE
    build:
      context: ./
      dockerfile: Dockerfile
      # IMPORTANT: pass all ARGs used in Dockerfile here to allow optional override from .env file
      args:
        BUILD_TARGET: ${BUILD_TARGET}
        DOMAIN: ${DOMAIN}
        MIG_SVN_REV: ${MIG_SVN_REV}
        EMULATE_FLAVOR: ${EMULATE_FLAVOR}
        EMULATE_FQDN: ${EMULATE_FQDN}
    container_name: migrid
    environment:
      TZ: Europe/Copenhagen
      # RUN_SERVICES specifies which daemons to launch
      # TODO: split out network services into individual containers
      #RUN_SERVICES: httpd script monitor sshmux events cron transfers openid sftp sftpsubsys webdavs ftps notify imnotify vmproxy
      RUN_SERVICES: httpd script monitor sshmux events cron transfers imnotify vmproxy
    depends_on:
      - devdns
    networks:
      default:
        aliases:
          - www.migrid.test
          - cert.migrid.test
          - ext.migrid.test
          - oid.migrid.test
          - sid.migrid.test
    volumes:
      - type: volume
        source: httpd
        target: /etc/httpd/
      - type: volume
        source: mig
        target: /home/mig/mig
      - type: volume
        source: certs
        target: /etc/httpd/MiG-certificates
      - type: volume
        source: state
        target: /home/mig/state
    env_file:
      - migrid-httpd.env
    command: /app/docker-entry.sh -u test@migrid.test -p TestPw0rd

  migrid-io:
    image: nielsbohr/migrid:$BUILD_TYPE
    build:
      context: ./
      dockerfile: Dockerfile
      # IMPORTANT: pass all ARGs used in Dockerfile here to allow optional override from .env file
      args:
        BUILD_TARGET: ${BUILD_TARGET}
        DOMAIN: ${DOMAIN}
        MIG_SVN_REV: ${MIG_SVN_REV}
        EMULATE_FLAVOR: ${EMULATE_FLAVOR}
        EMULATE_FQDN: ${EMULATE_FQDN}
    container_name: migrid-io
    environment:
      TZ: Europe/Copenhagen
      # RUN_SERVICES specifies which daemons to launch
      # TODO: split out network services into individual containers
      RUN_SERVICES: openid sftp sftpsubsys webdavs ftps notify
    depends_on:
      - migrid
    ports:
      - "2222:2222"
      - "4443:4443"
      - "8021:8021"
      - "8443:8443"
      - "22222:22222"
    networks:
      default:
        aliases:
          - io.migrid.test
    volumes:
      - type: volume
        source: httpd
        target: /etc/httpd/
      - type: volume
        source: mig
        target: /home/mig/mig
      - type: volume
        source: certs
        target: /etc/httpd/MiG-certificates
      - type: volume
        source: state
        target: /home/mig/state
    command: /app/docker-entry.sh

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - migrid
    ports:
    - "80:80"
    - "443:443"
    - "444:444"
    - "445:445"
    - "446:446"
    - "447:447"
    - "448:448"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx-proxy.conf:/etc/nginx/conf.d/migrid.conf
    - ./nginx-harden-https.conf:/etc/nginx/harden-https.conf
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/www.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/cert.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/ext.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/oid.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.crt:/etc/nginx/certs/sid.migrid.test.crt
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/www.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/cert.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/ext.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/oid.migrid.test.key
    - ./certs/MiG/*.migrid.test/server.key:/etc/nginx/certs/sid.migrid.test.key
    - ./certs/dhparams.pem:/etc/nginx/dhparam/dhparam.pem

volumes:
  certs:
    driver: local
    driver_opts:
      # Volume for generated certificates (provided by migrid)
      type: none
      device: $PWD/certs
      o: bind

  httpd:
    # Volume used for httpd config (provided by migrid)
    driver: local
    driver_opts:
      type: none
      device: $PWD/httpd
      o: bind

  mig:
    # Volume used to contain the migrid configuration (provided by migrid)
    driver: local
    driver_opts:
      type: none
      device: $PWD/mig
      o: bind

  state:
      # Volume used to contain the migrid state (provided by migrid)
      driver: local
      driver_opts:
        type: none
        device: $PWD/state
        o: bind
