version: '3.2'

services:
  docker-migrid:
    image: nielsbohr/migrid:edge
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - type: volume
        source: certs
        target: /home/mig/certs
    env_file:
      - httpd.env
    command: httpd -D FOREGROUND

volumes:
  certs:
